# Generated by Django 2.2 on 2019-04-16 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hezhi',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hezhi',
            name='lunchBoxCount',
            field=models.IntegerField(default=0),
        ),
    ]
