# Generated by Django 2.2 on 2019-04-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
