# Generated by Django 2.2 on 2019-04-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('openid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
